use glam::Vec3A;
use rayon::prelude::*;

use radia_core::csg::World;
use radia_core::primitive::Ray;
use radia_core::source::PointSource;

/// Calculate the total integrated dose rate from multiple point sources over an energy spectrum.
/// This loops over both energy divisions and source divisions, and is optimized by extracting
/// ray intersections once per point source instead of once per energy group.
///
/// * `get_mu` - A closure `Fn(usize, usize) -> f32` mapped to `(material_id, energy_group)`.
///   (Typically generated by `MuTable::into_closure()`).
/// * `get_buildup` - A closure `Fn(usize, f32) -> f32` mapped to `(energy_group, optical_thickness)`
///   returning the build-up factor.
/// * `world` - The CSG defined world.
/// * `conversion_factors` - A slice of factors (e.g. from flux to effective dose) with one element
///   per energy group.
/// * `detector_position` - The 3D coordinates `Vec3A` of the detector.
/// * `sources` - A slice of `PointSource` instances to integrate over.
pub fn calculate_dose_rate<F, B>(
    get_mu: &F,
    get_buildup: &B,
    world: &World,
    conversion_factors: &[f32],
    detector_position: Vec3A,
    sources: &[PointSource],
) -> f32
where
    F: Fn(usize, usize) -> f32,
    B: Fn(usize, f32) -> f32,
{
    let mut total_dose = 0.0;
    let num_groups = conversion_factors.len();
    let mut segments_buffer = Vec::with_capacity(32); // pre-allocate for performance
    let mut buffer_ts = Vec::with_capacity(64); // pre-allocate for performance
    let mut buffer_merged_ts = Vec::with_capacity(64); // pre-allocate for performance

    // Loop over source division
    for source in sources {
        let diff = detector_position - source.position;

        let distance_sq = diff.length_squared();
        if distance_sq < 1e-10 {
            // Detector is exactly at a source position, avoid infinity
            continue;
        }

        let ray = Ray {
            origin: source.position,
            vector: diff,
        };

        // Get material segments once for this source (Optimized step for speed)
        world.get_ray_segments(
            &ray,
            &mut segments_buffer,
            &mut buffer_ts,
            &mut buffer_merged_ts,
        );

        let geometric_attenuation = 1.0 / (4.0 * std::f32::consts::PI * distance_sq);

        let mut source_dose = 0.0;

        // Loop over energy division
        for i in 0..num_groups {
            let mut optical_thickness = 0.0;
            // Sum mu * x over all traversed cells
            for &(mat_id, length) in &segments_buffer {
                optical_thickness += get_mu(mat_id as usize, i) * length;
            }

            let buildup = get_buildup(i, optical_thickness);
            let material_attenuation = (-optical_thickness).exp();

            // flux to dose conversion
            source_dose += conversion_factors[i] * buildup * material_attenuation;
        }

        total_dose += source.intensity * geometric_attenuation * source_dose;
    }

    total_dose
}

pub fn calculate_dose_rate_parallel<F, B>(
    get_mu: &F,
    get_buildup: &B,
    world: &World,
    conversion_factors: &[f32],
    detector_position: Vec3A,
    sources: &[PointSource],
    chunk_size: usize,
) -> f32
where
    F: Fn(usize, usize) -> f32 + Sync,
    B: Fn(usize, f32) -> f32 + Sync,
{
    sources
        .par_chunks(chunk_size)
        .map(|source_chunk| {
            calculate_dose_rate(
                get_mu,
                get_buildup,
                world,
                conversion_factors,
                detector_position,
                source_chunk,
            )
        })
        .sum()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_unshielded_point_source_spectrum() {
        let world = World {
            primitives: vec![],
            cells: vec![],
        };

        let source = PointSource {
            position: Vec3A::ZERO,
            intensity: 100.0,
        };

        // Detector at r = 10.0
        let detector = Vec3A::new(10.0, 0.0, 0.0);

        let get_mu = |_, _| 0.0;
        let get_buildup = |_, _| 1.0;

        let conversion_factors = vec![1.0];

        let dose = calculate_dose_rate(
            &get_mu,
            &get_buildup,
            &world,
            &conversion_factors,
            detector,
            &[source],
        );

        let expected_geometric = 1.0 / (4.0 * std::f32::consts::PI * 100.0);
        let expected_dose = 100.0 * expected_geometric * 1.0;
        assert!((dose - expected_dose).abs() < 1e-6);
    }
}
