use crate::csg::World;
use crate::shape::Ray;
use crate::source::PointSource;

/// Calculate the total integrated dose rate from multiple point sources over an energy spectrum.
/// This loops over both energy divisions and source divisions, and is optimized by extracting
/// ray intersections once per point source instead of once per energy group.
///
/// * `get_mu` - A closure `Fn(usize, usize) -> f64` mapped to `(material_id, energy_group)`.
///   (Typically generated by `MuTable::into_closure()`).
/// * `get_buildup` - A closure `Fn(usize, f64) -> f64` mapped to `(energy_group, optical_thickness)`
///   returning the build-up factor.
/// * `world` - The CSG defined world.
/// * `conversion_factors` - A slice of factors (e.g. from flux to effective dose) with one element
///   per energy group.
/// * `detector_position` - The 3D coordinates `(x, y, z)` of the detector.
/// * `sources` - A slice of `PointSource` instances to integrate over.
pub fn calculate_dose_rate_spectrum<F, B>(
    get_mu: &F,
    get_buildup: &B,
    world: &World,
    conversion_factors: &[f64],
    detector_position: (f64, f64, f64),
    sources: &[PointSource],
) -> f64
where
    F: Fn(usize, usize) -> f64,
    B: Fn(usize, f64) -> f64,
{
    let mut total_dose = 0.0;
    let num_groups = conversion_factors.len();

    // Loop over source division
    for source in sources {
        let dx = detector_position.0 - source.position.0;
        let dy = detector_position.1 - source.position.1;
        let dz = detector_position.2 - source.position.2;

        let distance_sq = dx * dx + dy * dy + dz * dz;
        if distance_sq < 1e-10 {
            // Detector is exactly at a source position, avoid infinity
            continue;
        }

        let distance = distance_sq.sqrt();
        let direction_dir = (dx / distance, dy / distance, dz / distance);

        let ray = Ray {
            origin: source.position,
            direction: direction_dir,
        };

        // Get material segments once for this source (Optimized step for speed)
        let segments = world.get_ray_segments(&ray);

        let geometric_attenuation = 1.0 / (4.0 * std::f64::consts::PI * distance_sq);

        let mut source_dose = 0.0;

        // Loop over energy division
        for i in 0..num_groups {
            let mut optical_thickness = 0.0;
            // Sum mu * x over all traversed cells
            for &(mat_id, length) in &segments {
                optical_thickness += get_mu(mat_id as usize, i) * length;
            }

            let buildup = get_buildup(i, optical_thickness);
            let material_attenuation = (-optical_thickness).exp();

            // flux to dose conversion
            source_dose += conversion_factors[i] * buildup * material_attenuation;
        }

        total_dose += source.intensity * geometric_attenuation * source_dose;
    }

    total_dose
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    #[test]
    fn test_unshielded_point_source_spectrum() {
        let world = World {
            shapes: HashMap::new(),
            cells: vec![],
        };

        let source = PointSource {
            position: (0.0, 0.0, 0.0),
            intensity: 100.0,
        };

        // Detector at r = 10.0
        let detector = (10.0, 0.0, 0.0);

        let get_mu = |_, _| 0.0;
        let get_buildup = |_, _| 1.0;

        let conversion_factors = vec![1.0];

        let dose = calculate_dose_rate_spectrum(
            &get_mu,
            &get_buildup,
            &world,
            &conversion_factors,
            detector,
            &[source],
        );

        let expected_geometric = 1.0 / (4.0 * std::f64::consts::PI * 100.0);
        let expected_dose = 100.0 * expected_geometric * 1.0;
        assert!((dose - expected_dose).abs() < 1e-6);
    }
}
