pub const EPSILON: f32 = 1e-6; // length [cm]
pub const EPSILON2: f32 = 1e-12; // length^2 [cm^2]
pub const T_EPSILON: f32 = 1e-6; // parameter [unitless]
pub const O_EPSILON: f32 = 1e-6; // optical thickness [unitless]
pub const E_EPSILON: f32 = 1e-9; // energy [MeV]
